# Generated by Django 3.1.2 on 2020-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='level',
            field=models.CharField(default='HND I', max_length=20, verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='level',
            field=models.CharField(default='HND I', max_length=20, verbose_name='Class'),
            preserve_default=False,
        ),
    ]
