# Generated by Django 3.1.2 on 2020-10-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0003_auto_20201011_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='assresponse',
            name='level',
            field=models.CharField(default='HND I', max_length=20, verbose_name='Class'),
            preserve_default=False,
        ),
    ]
