# Generated by Django 3.1.2 on 2020-10-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0005_lecture_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='topic',
        ),
    ]
