# Generated by Django 3.1.2 on 2020-10-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0006_auto_20201011_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='handout',
            field=models.FileField(blank=True, help_text='Please upload material(s) for this course', null=True, upload_to='lecturer/Lectures'),
        ),
    ]
