# Generated by Django 3.1.2 on 2020-10-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0007_auto_20201011_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course_unit',
            field=models.CharField(default=2, max_length=4),
            preserve_default=False,
        ),
    ]
