# Generated by Django 3.1.2 on 2020-10-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0008_lecture_course_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssPortal.lecture'),
        ),
    ]
