# Generated by Django 3.1.2 on 2020-10-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0010_auto_20201011_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assresponse',
            name='question',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to='AssPortal.assignment'),
            preserve_default=False,
        ),
    ]
