# Generated by Django 3.1.2 on 2020-10-11 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssPortal', '0011_auto_20201012_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assresponse',
            name='matric_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
