# Generated by Django 3.1.2 on 2020-10-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0013_auto_20201012_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assresponse',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assresponse',
            name='matric_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='assresponse',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
