# Generated by Django 3.1.2 on 2020-10-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0017_assignment_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='lecturer',
        ),
    ]
