# Generated by Django 3.1.2 on 2020-10-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0022_auto_20201013_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['date_uploaded']},
        ),
    ]
