# Generated by Django 3.1.2 on 2020-10-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0023_auto_20201013_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-date_uploaded']},
        ),
    ]
