# Generated by Django 3.1.2 on 2020-10-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0024_auto_20201013_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('ND I', 'ND I'), ('ND II', 'ND II'), ('HND I', 'HND I'), ('HND II', 'HND II')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
