# Generated by Django 3.1.2 on 2020-10-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0026_student_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
