# Generated by Django 3.1.2 on 2020-10-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0027_lecturer_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='is_student',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='is_lecturer',
            field=models.BooleanField(default=True),
        ),
    ]
