# Generated by Django 3.1.2 on 2020-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0028_auto_20201013_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
