# Generated by Django 3.1.2 on 2020-10-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0029_auto_20201014_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
