# Generated by Django 3.1.2 on 2020-10-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0030_auto_20201015_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
