# Generated by Django 3.1.2 on 2020-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0031_auto_20201015_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='is_lecturer',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
