# Generated by Django 3.1.2 on 2020-10-16 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0032_auto_20201015_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assresponse',
            name='matric_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssPortal.student'),
        ),
    ]
