# Generated by Django 3.1.2 on 2020-10-16 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0034_assresponse_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assresponse',
            old_name='assignment',
            new_name='question',
        ),
    ]
