# Generated by Django 3.1.2 on 2020-10-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0036_lecture_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecturer',
        ),
    ]
