# Generated by Django 3.1.2 on 2020-10-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0037_remove_lecture_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecturer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='AssPortal.lecturer'),
            preserve_default=False,
        ),
    ]
