# Generated by Django 3.1.2 on 2020-10-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0039_auto_20201022_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
