# Generated by Django 3.1.2 on 2020-10-24 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssPortal', '0042_auto_20201023_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='assresponse',
            name='lecturer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
