# Generated by Django 3.1.2 on 2020-10-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0043_assresponse_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assresponse',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssPortal.lecturer'),
        ),
    ]
