# Generated by Django 3.1.2 on 2020-10-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0044_auto_20201024_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assresponse',
            name='lecturer',
        ),
    ]
