# Generated by Django 3.1.2 on 2020-10-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0047_remove_assresponse_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assresponse',
            name='lecturer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
