# Generated by Django 3.1.2 on 2020-10-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0048_assresponse_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='semester',
            field=models.CharField(choices=[('FIRST SEMESTER', 'FIRST SEMESTER'), ('SECOND SEMESTER', 'SECOND SEMESTER')], default='FIRST SEMESTER', max_length=30),
            preserve_default=False,
        ),
    ]
