# Generated by Django 3.1.2 on 2020-11-02 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssPortal', '0050_assresponse_is_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='score',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(max_length=30)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssPortal.assignment')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssPortal.student')),
            ],
        ),
    ]
