# Generated by Django 3.1.2 on 2020-11-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0051_auto_20201102_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.PositiveIntegerField(default=30, max_length=30),
        ),
    ]
