# Generated by Django 3.1.2 on 2020-11-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0053_auto_20201102_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssPortal.lecturer'),
        ),
    ]
