# Generated by Django 3.1.2 on 2020-11-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0054_auto_20201102_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='remarks',
            field=models.CharField(default='Good', max_length=100),
            preserve_default=False,
        ),
    ]
