# Generated by Django 3.1.2 on 2020-11-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0056_auto_20201102_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.AddField(
            model_name='grade',
            name='course_code',
            field=models.CharField(default='COM 411', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='matric_no',
            field=models.CharField(default='15/69/0250', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='question',
            field=models.CharField(default='Mobile Application', max_length=100),
            preserve_default=False,
        ),
    ]
