# Generated by Django 3.1.2 on 2020-11-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0057_auto_20201102_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assresponse',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
