# Generated by Django 3.1.2 on 2020-11-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0059_auto_20201102_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='question',
            field=models.CharField(default='What Do You Understand By Lexical Analysis?', max_length=100),
            preserve_default=False,
        ),
    ]
