# Generated by Django 3.1.2 on 2020-11-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0060_grade_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='score',
        ),
        migrations.AddField(
            model_name='grade',
            name='mark',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
