# Generated by Django 3.1.2 on 2020-11-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0061_auto_20201102_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='slug_course_code',
            field=models.SlugField(default='COM 329', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assresponse',
            name='slug_course_code',
            field=models.SlugField(default='COM 329', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='slug_course_code',
            field=models.SlugField(default='COM 329', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='grade',
            name='mark',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
