# Generated by Django 3.1.2 on 2020-11-03 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0063_auto_20201103_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='mark',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
