# Generated by Django 3.1.2 on 2020-11-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0064_auto_20201103_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.CharField(default='HND II', max_length=20),
            preserve_default=False,
        ),
    ]
