# Generated by Django 3.1.2 on 2020-11-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0065_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='matric_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssPortal.student'),
        ),
    ]
