# Generated by Django 3.1.2 on 2020-11-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0066_auto_20201109_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='matric_no',
            new_name='student',
        ),
    ]
