# Generated by Django 3.1.2 on 2020-11-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0070_auto_20201109_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AssPortal.student'),
            preserve_default=False,
        ),
    ]
