# Generated by Django 3.1.2 on 2020-11-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0071_auto_20201109_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='slug_course_code',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='slug_course_code',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
