# Generated by Django 3.1.2 on 2020-11-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0072_auto_20201110_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='slug_course_code',
            new_name='slug',
        ),
    ]
