# Generated by Django 3.1.2 on 2020-11-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0074_auto_20201110_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='assresponse',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
