# Generated by Django 3.1.2 on 2020-12-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0076_category_replies_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replies',
            new_name='Reply',
        ),
    ]
