# Generated by Django 3.1.2 on 2020-12-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssPortal', '0077_auto_20201224_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
